### ISSUE TITLE
DutchX crashes

### ISSUE THREAD

**Issue by clesaege** [kleros/fairdex#1]
DutchX does not load. Maybe it happens when there is no auction running.

Chrome:
![bug](https://user-images.githubusercontent.com/8873352/78706634-5110aa00-7907-11ea-81ce-974a83d4b501.png)

Firefox:
![bug2](https://user-images.githubusercontent.com/8873352/78706703-6c7bb500-7907-11ea-925d-b7e869f0ef00.png)

**Comment by eccentricexit** [comment]
The issue seems to be gone. It looks like the provider was just timing out.

**Comment by eccentricexit** [comment]
Request is timing out more frequently. It needs to be fixed.
